version: "3"
services:
  mysql:
    image: mysql:8.0.35
    command: --local-infile=1
    container_name: "mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogsample
